# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171005_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='validation_key',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
