# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171005_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailuser',
            name='is_staff',
        ),
    ]
