# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='is_terms_conditions_accept',
            field=models.BooleanField(default=False),
        ),
    ]
