# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_emailuser_is_terms_conditions_accept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailuser',
            old_name='is_terms_conditions_accept',
            new_name='is_terms_conditions_accepted',
        ),
    ]
