# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_termsconditions'),
        ('accounts', '0009_auto_20171011_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='terms_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.TermsConditions'),
        ),
    ]
