# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_emailuser_terms_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='terms_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.TermsConditions'),
        ),
    ]
