# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20171024_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
