# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20171026_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='is_seller_approved',
            field=models.BooleanField(default=False),
        ),
    ]
