# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_emailuser_is_seller_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='braintree_customer_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
