# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_emailuser_braintree_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
