# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20171206_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Country Latitude'),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Country Longitude'),
        ),
    ]
