# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20171208_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='country',
            name='longitude',
        ),
        migrations.AddField(
            model_name='state',
            name='left',
            field=models.FloatField(blank=True, null=True, verbose_name='Country Longitude'),
        ),
        migrations.AddField(
            model_name='state',
            name='top',
            field=models.FloatField(blank=True, null=True, verbose_name='Country Latitude'),
        ),
    ]
