# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_city_postcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'City'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Country'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'State'},
        ),
    ]
