# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20171214_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailuser',
            name='company_logo',
        ),
    ]
