# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_emailuser_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='is_social',
            field=models.BooleanField(default=False),
        ),
    ]
