# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 09:02
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20180130_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='background_image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='BackgroundImages/'),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='company_logo',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='CompanyLogo/'),
        ),
    ]
