# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_groupcountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcountry',
            name='country',
        ),
        migrations.AddField(
            model_name='groupcountry',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
