# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-10 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_country_group_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_symbol',
            field=models.TextField(blank=True, null=True),
        ),
    ]
