# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-10 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_country_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
