# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_country_weight_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='braintree_alpha3_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
