# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_country_braintree_alpha3_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='braintree_alpha3_code',
            new_name='braintree_merchanr_id',
        ),
    ]
