# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20180405_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='braintree_merchanr_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
