# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20180405_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerAvailableCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Country')),
            ],
        ),
    ]
