# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-02 03:54
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_buyeravailablecountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='background_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='BackgroundImages/'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='company_logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='CompanyLogo/'),
        ),
    ]
