# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-16 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20180502_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
