# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_country_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='COFTOUSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField(default=1)),
                ('usd', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
