# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_coftousd'),
    ]

    operations = [
        migrations.AddField(
            model_name='coftousd',
            name='destination_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coftousd',
            name='usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
