# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20180517_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coftousd',
            options={'verbose_name_plural': 'COF TO USD'},
        ),
        migrations.AddField(
            model_name='coftousd',
            name='coin_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
