# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-05 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20180905_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.City'),
        ),
    ]
