# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-02 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20180905_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
